export const NEED_LOGIN = "NEED_LOGIN";
export const REFRESH_XIANGMU_LIST = "REFRESH_XIANGMU_LIST";
export const REFRESH_EDITING_XIANGMU = "REFRESH_EDITING_XIANGMU";
export const REFRESH_GONGSI_JIESUANRI = "REFRESH_GONGSI_JIESUANRI";
export const REFRESH_YONGHU_JIESUANRI = "REFRESH_YONGHU_JIESUANRI";